Repository frc5024/InfiniteRecharge, pull requests merged in 2020-02, with the labels that each got.

#128 Fixed Deprication.. I think
  src/main/java/frc/lib5k/components/BlinkinDriver.java
  src/main/java/frc/lib5k/components/Compass.java
  src/main/java/frc/lib5k/control/PID.java
  src/main/java/frc/lib5k/control/PIDv2.java
Labels: bug, library

#132 Fixed The UTF Issue
  src/main/java/frc/lib5k/components/limelight/Limelight.java
Labels: bug, cleanup

#129 Add Driver dashboard settings
  imgui.ini
  src/main/java/frc/robot/Dashboard.java
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/autonomous/Chooser.java
  src/main/java/frc/robot/subsystems/DriveTrain.java
  src/main/java/frc/robot/subsystems/cellmech/Shooter.java
  src/main/shuffleboard/shuffleboard.json
Labels: feature

#134 Panel-States into color-sensor to ensure safety.
  src/main/java/frc/lib5k/components/ColorSensor5k.java
  src/main/java/frc/lib5k/utils/ColorUtils.java
  src/main/java/frc/robot/GameData.java
  src/main/java/frc/robot/OI.java
  src/main/java/frc/robot/RobotConstants.java
  src/main/java/frc/robot/subsystems/PanelManipulator.java
Labels: feature

#126 Clean up superstructure, operator inputs, update intake to use new harwdare setup, set up PID for shooter, and more
  src/main/java/frc/lib5k/simulation/wrappers/SimTalon.java
  src/main/java/frc/robot/OI.java
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/RobotConstants.java
  src/main/java/frc/robot/autonomous/actions/cells/IntakeCells.java
  src/main/java/frc/robot/commands/DriveControl.java
  src/main/java/frc/robot/commands/ManualControl.java
  src/main/java/frc/robot/commands/OperatorControl.java
  src/main/java/frc/robot/commands/actions/AutoAlign.java
  src/main/java/frc/robot/subsystems/CellSuperstructure.java
  src/main/java/frc/robot/subsystems/cellmech/Hopper.java
  src/main/java/frc/robot/subsystems/cellmech/Intake.java
  src/main/java/frc/robot/subsystems/cellmech/Shooter.java
Labels: cleanup, documentation, feature, library

#135 Add dashboard widgets for climber
  imgui.ini
  src/main/java/frc/lib5k/components/AutoCamera.java
  src/main/java/frc/lib5k/components/BlinkinDriver.java
  src/main/java/frc/lib5k/components/Compass.java
  src/main/java/frc/lib5k/components/limelight/Limelight.java
  src/main/java/frc/lib5k/control/PID.java
  src/main/java/frc/lib5k/control/PIDv2.java
  src/main/java/frc/robot/Dashboard.java
  src/main/java/frc/robot/OI.java
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/autonomous/Chooser.java
  src/main/java/frc/robot/commands/ClimbController.java
  src/main/java/frc/robot/commands/ClimbProcess.java
  src/main/java/frc/robot/subsystems/Climber.java
  src/main/java/frc/robot/subsystems/DriveTrain.java
  src/main/java/frc/robot/subsystems/cellmech/Shooter.java
  src/main/shuffleboard/shuffleboard.json
Labels: documentation, feature, library

#136 Add LinearActuator, LineBreak, HallEffect, and an Interface for binary sensors
  src/main/java/frc/lib5k/components/LinearActuator.java
  src/main/java/frc/lib5k/components/motors/TalonSRXCollection.java
  src/main/java/frc/lib5k/components/motors/VictorSPXCollection.java
  src/main/java/frc/lib5k/components/sensors/EncoderBase.java
  src/main/java/frc/lib5k/components/sensors/HallEffect.java
  src/main/java/frc/lib5k/components/sensors/LineBreak.java
  src/main/java/frc/lib5k/components/sensors/interfaces/IBinarySensor.java
  src/main/java/frc/lib5k/components/sensors/interfaces/IEncoderProvider.java
Labels: library

#137 Update Intake systems to use new component wrappers
  src/main/java/frc/lib5k/components/LinearActuator.java
  src/main/java/frc/lib5k/components/motors/TalonSRXCollection.java
  src/main/java/frc/lib5k/components/motors/VictorSPXCollection.java
  src/main/java/frc/lib5k/components/sensors/EncoderBase.java
  src/main/java/frc/lib5k/components/sensors/HallEffect.java
  src/main/java/frc/lib5k/components/sensors/LineBreak.java
  src/main/java/frc/lib5k/components/sensors/interfaces/IBinarySensor.java
  src/main/java/frc/lib5k/components/sensors/interfaces/IEncoderProvider.java
  src/main/java/frc/robot/subsystems/cellmech/Hopper.java
  src/main/java/frc/robot/subsystems/cellmech/Intake.java
Labels: documentation, feature

#150 Add gradle wrapper integrity validation to CI pipeline
  .github/workflows/gradlevalidation.yml
Labels: feature

#152 Remove jaci's pathfinder as a project dependancy
  README.md
  src/main/java/frc/lib5k/kinematics/FieldPosition.java
  src/main/java/frc/lib5k/kinematics/motionprofiling/MotionProfile.java
  src/main/java/frc/lib5k/kinematics/motionprofiling/Motionprofiler.java
  vendordeps/PathfinderOLD.json
Labels: bug, cleanup

#149 Add intake freezing feature
  .github/workflows/gradlevalidation.yml
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/RobotConstants.java
  src/main/java/frc/robot/subsystems/cellmech/Hopper.java
  src/main/java/frc/robot/subsystems/cellmech/Intake.java
Labels: feature

#153 Add actually tested superstructure code
  .github/workflows/gradlevalidation.yml
  README.md
  docs/sensormapping.md
  src/main/java/frc/lib5k/kinematics/FieldPosition.java
  src/main/java/frc/lib5k/kinematics/motionprofiling/MotionProfile.java
  src/main/java/frc/lib5k/kinematics/motionprofiling/Motionprofiler.java
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/RobotConstants.java
  src/main/java/frc/robot/autonomous/actions/cells/ShootCells.java
  src/main/java/frc/robot/subsystems/CellSuperstructure.java
  src/main/java/frc/robot/subsystems/cellmech/Hopper.java
  src/main/java/frc/robot/subsystems/cellmech/Intake.java
  src/main/java/frc/robot/subsystems/cellmech/Shooter.java
  vendordeps/PathfinderOLD.json
Labels: cleanup, feature

#146 Integrate Superstructure and Climber into master
  README.md
  characterization/Piperservant20200206-1721.json
  characterization/robotconfig.py
  docs/sensormapping.md
  src/main/java/frc/lib5k/components/AutoCamera.java
  src/main/java/frc/lib5k/components/LinearActuator.java
  src/main/java/frc/lib5k/components/pneumatics/LazySolenoid.java
  src/main/java/frc/lib5k/components/sensors/LimitSwitch.java
  src/main/java/frc/lib5k/roborio/RR_HAL.java
  src/main/java/frc/lib5k/simulation/wrappers/SimTalon.java
  src/main/java/frc/robot/Dashboard.java
  src/main/java/frc/robot/OI.java
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/RobotConstants.java
  src/main/java/frc/robot/autonomous/Chooser.java
  src/main/java/frc/robot/autonomous/actions/DriveToCommand.java
  src/main/java/frc/robot/autonomous/actions/LinePath.java
  src/main/java/frc/robot/autonomous/actions/cells/IntakeCells.java
  src/main/java/frc/robot/autonomous/actions/cells/ShootCells.java
  src/main/java/frc/robot/autonomous/actions/cells/StopCells.java
  src/main/java/frc/robot/autonomous/actions/cells/UnjamCells.java
  src/main/java/frc/robot/autonomous/helpers/PathGenerator.java
  src/main/java/frc/robot/autonomous/paths/balls/ballsScoreTrench.java
  src/main/java/frc/robot/autonomous/paths/score/ScoreCenter.java
  src/main/java/frc/robot/autonomous/paths/score/ScoreGetBalls.java
  src/main/java/frc/robot/autonomous/paths/score/ScorePickupRight.java
  src/main/java/frc/robot/autonomous/paths/score/ScoreRight.java
  src/main/java/frc/robot/commands/ClimbController.java
  src/main/java/frc/robot/commands/DriveControl.java
  src/main/java/frc/robot/commands/OperatorControl.java
  src/main/java/frc/robot/commands/ShooterTester.java
  src/main/java/frc/robot/commands/actions/AutoAlign.java
  src/main/java/frc/robot/subsystems/CellSuperstructure.java
  src/main/java/frc/robot/subsystems/Climber.java
  src/main/java/frc/robot/subsystems/DriveTrain.java
  src/main/java/frc/robot/subsystems/cellmech/Hopper.java
  src/main/java/frc/robot/subsystems/cellmech/Intake.java
  src/main/java/frc/robot/subsystems/cellmech/Shooter.java
Labels: cleanup, documentation, feature, library

#154 Re-map shooter button to reduce confusion
  src/main/java/frc/robot/OI.java
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/RobotConstants.java
  src/main/java/frc/robot/autonomous/actions/cells/UnjamCells.java
  src/main/java/frc/robot/commands/OperatorControl.java
  src/main/java/frc/robot/subsystems/CellSuperstructure.java
  src/main/java/frc/robot/subsystems/cellmech/Hopper.java
  src/main/java/frc/robot/subsystems/cellmech/Intake.java
Labels: cleanup

#155 Make the Limelight switch camera modes while aiming
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/commands/actions/AutoAlign.java
Labels: feature

#156 Tweak shooter code
  src/main/java/frc/lib5k/spatial/LocalizationEngine.java
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/RobotConstants.java
  src/main/java/frc/robot/autonomous/actions/cells/ShootCells.java
  src/main/java/frc/robot/commands/actions/AutoAlign.java
  src/main/java/frc/robot/subsystems/cellmech/Hopper.java
  src/main/java/frc/robot/subsystems/cellmech/Shooter.java
Labels: cleanup, documentation

#163 Add a Python script for graphing the shooter velocity in real-time
  imgui.ini
  scripts/hardware-tuning/shooterplot.py
  src/main/java/frc/lib5k/components/AutoCamera.java
  src/main/java/frc/lib5k/utils/telemetry/FlywheelTuner.java
  src/main/java/frc/robot/RobotConstants.java
  src/main/java/frc/robot/subsystems/cellmech/Hopper.java
  src/main/java/frc/robot/subsystems/cellmech/Intake.java
  src/main/java/frc/robot/subsystems/cellmech/Shooter.java
Labels: feature, library

#176 Switch shooter to voltage control to improve spinup times
  src/main/java/frc/robot/RobotConstants.java
  src/main/java/frc/robot/subsystems/cellmech/Intake.java
  src/main/java/frc/robot/subsystems/cellmech/Shooter.java
Labels: feature

#177 Add control panel control
  .idea/vcs.xml
  InfiniteRecharge.iml
  InfiniteRecharge.ipr
  InfiniteRecharge.iws
  src/main/java/frc/lib5k/components/AutoCamera.java
  src/main/java/frc/lib5k/components/sensors/ColorSensor5k.java
  src/main/java/frc/lib5k/utils/Color5k.java
  src/main/java/frc/lib5k/utils/Mathutils.java
  src/main/java/frc/robot/OI.java
  src/main/java/frc/robot/RobotConstants.java
  src/main/java/frc/robot/autonomous/Chooser.java
  src/main/java/frc/robot/commands/OperatorControl.java
  src/main/java/frc/robot/commands/actions/controlpanel/PositionPanel.java
  src/main/java/frc/robot/commands/actions/controlpanel/RotatePanel.java
  src/main/java/frc/robot/subsystems/PanelManipulator.java
Labels: feature

#171 Turn off Limelight LED on robot enable
  src/main/java/frc/robot/Robot.java
Labels: cleanup

#180 Tune PID for a quick spinup time on shooter
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/RobotConstants.java
  src/main/java/frc/robot/vision/Limelight2.java
Labels: cleanup

#181 Changed a button for Percy
  imgui.ini
  src/main/java/frc/robot/OI.java
  src/main/java/frc/robot/commands/OperatorControl.java
  src/main/java/frc/robot/commands/actions/LowerBalls.java
  src/main/java/frc/robot/subsystems/CellSuperstructure.java
  src/main/java/frc/robot/subsystems/cellmech/Hopper.java
Labels: feature

#183 Add full support for control panel interaction
  docs/operation.md
  src/main/java/frc/robot/OI.java
  src/main/java/frc/robot/commands/OperatorControl.java
  src/main/java/frc/robot/commands/actions/controlpanel/TimePanel.java
  src/main/java/frc/robot/subsystems/PanelManipulator.java
Labels: cleanup, feature

#187 Hook FieldSim into IMGUI's Field2D
  imgui.ini
  src/main/java/frc/lib5k/simulation/Field2d.java
  src/main/java/frc/lib5k/simulation/wpihooks/imgui/IMGUIFieldReporter.java
  src/main/java/frc/robot/Robot.java
Labels: cleanup, feature

#188 Add runner script to start robot simulation on linux systems
  imgui.ini
  run-simulation.sh
Labels: feature

#185 Tweak intake constants & Disable ball counting
  src/main/java/frc/robot/RobotConstants.java
  src/main/java/frc/robot/subsystems/CellSuperstructure.java
Labels: Discussion, cleanup, help wanted

#190 Move climb controls over to driver controller
  docs/operation.md
  src/main/java/frc/robot/OI.java
Labels: feature

#191 Add hopper cell count overrides
  docs/operation.md
  src/main/java/frc/robot/OI.java
  src/main/java/frc/robot/RobotConstants.java
  src/main/java/frc/robot/autonomous/actions/cells/UnjamUpCells.java
  src/main/java/frc/robot/commands/OperatorControl.java
  src/main/java/frc/robot/subsystems/CellSuperstructure.java
  src/main/java/frc/robot/subsystems/cellmech/Hopper.java
Labels: feature

#197 Clean up the runner script a bit, and force it to kill the sim proc
  imgui.ini
  run-simulation.sh
Labels: feature

#198 Add first auton path
  .vscode/launch.json
  imgui.ini
  src/main/java/frc/lib5k/kinematics/MovementPlanner.java
  src/main/java/frc/lib5k/kinematics/purepursuit/Follower.java
  src/main/java/frc/lib5k/kinematics/purepursuit/Path.java
  src/main/java/frc/lib5k/kinematics/purepursuit/PurePursuitController.java
  src/main/java/frc/lib5k/kinematics/statespace/models/DrivebaseState.java
  src/main/java/frc/lib5k/kinematics/systemdef/VelocityConstraint.java
  src/main/java/frc/lib5k/kinematics/systemdef/VelocityDefinition.java
  src/main/java/frc/lib5k/kinematics/unicycle/MotionController.java
  src/main/java/frc/lib5k/utils/Mathutils.java
  src/main/java/frc/robot/RobotConstants.java
  src/main/java/frc/robot/autonomous/Chooser.java
  src/main/java/frc/robot/autonomous/actions/DrivePath.java
  src/main/java/frc/robot/autonomous/actions/TrianglePath.java
  src/main/java/frc/robot/autonomous/actions/cells/IntakeCells.java
  src/main/java/frc/robot/autonomous/actions/cells/ShootCells.java
  src/main/java/frc/robot/autonomous/helpers/PathGenerator.java
  src/main/java/frc/robot/autonomous/paths/balls/ballsScoreTrench.java
  src/main/java/frc/robot/autonomous/paths/score/ScoreCenter.java
  src/main/java/frc/robot/autonomous/paths/score/ScoreGetBalls.java
  src/main/java/frc/robot/autonomous/paths/score/ScorePickupRight.java
  src/main/java/frc/robot/autonomous/paths/score/ScoreRight.java
  src/main/java/frc/robot/autonomous/paths/score/ScoreTwice.java
  src/main/java/frc/robot/autonomous/paths/test/TestPure.java
  src/main/java/frc/robot/autonomous/paths/test/TestReverse.java
  src/main/java/frc/robot/subsystems/DriveTrain.java
Labels: feature

#189 Add "slow mode" for a little more control while driving
  docs/operation.md
  src/main/java/frc/robot/OI.java
  src/main/java/frc/robot/RobotConstants.java
  src/main/java/frc/robot/commands/DriveControl.java
Labels: feature

#200 Add auto-aim support for multiple modes
  imgui.ini
  src/main/java/frc/robot/OI.java
  src/main/java/frc/robot/autonomous/actions/VisionAlign.java
  src/main/java/frc/robot/commands/DriveControl.java
  src/main/java/frc/robot/commands/actions/FreeSpaceAutoAim.java
  src/main/java/frc/robot/commands/actions/PivotAutoAim.java
  src/main/java/frc/robot/vision/SimVision.java
Labels: feature

#201 Buffer Limelight aiming params before auto-aiming
  src/main/java/frc/robot/RobotConstants.java
  src/main/java/frc/robot/commands/actions/FreeSpaceAutoAim.java
  src/main/java/frc/robot/commands/actions/PivotAutoAim.java
  src/main/java/frc/robot/commands/actions/alignment/FreeAim.java
  src/main/java/frc/robot/commands/actions/alignment/PivotAim.java
Labels: cleanup
