Repository frc5024/InfiniteRecharge, pull requests merged in 2020-03, with the labels that each got.

#205 Add DCBrushedMotor model
  src/main/java/frc/lib5k/kinematics/models/DCBrushedMotor.java
Labels: feature, library

#202 Reduce the amount of time the Limelight is turned on while pivot-aiming
  src/main/java/frc/robot/commands/actions/alignment/PivotAim.java
Labels: cleanup

#210 Add match analytics report to robot logs
  src/main/java/frc/robot/AnalyticsEngine.java
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/autonomous/actions/cells/UnjamCells.java
  src/main/java/frc/robot/autonomous/actions/cells/UnjamUpCells.java
  src/main/java/frc/robot/commands/ClimbController.java
  src/main/java/frc/robot/commands/OperatorControl.java
  src/main/java/frc/robot/commands/actions/alignment/FreeAim.java
  src/main/java/frc/robot/commands/actions/alignment/PivotAim.java
  src/main/java/frc/robot/commands/actions/controlpanel/TimePanel.java
  src/main/java/frc/robot/subsystems/cellmech/Hopper.java
Labels: feature

#214 Add limelight tweaks from final testing day
  2020default.vpr
  src/main/java/frc/robot/RobotConstants.java
  src/main/java/frc/robot/commands/actions/alignment/PivotAim.java
  src/main/limelight/2020default.vpr
Labels: feature

#212 Climber changes
  src/main/java/frc/robot/subsystems/Climber.java
Labels: feature

#220 Add script to live tail all logs on the RoboRIO during comps
  scripts/tools/taillogs.sh
Labels: feature, small task

#216 Add new auton command to set ABS shooter velocity in autonomous, and auto-reset at the start of teleop.
  imgui.ini
  scripts/tools/taillogs.sh
  src/main/java/frc/lib5k/components/SmartServo.java
  src/main/java/frc/robot/RobotConstants.java
  src/main/java/frc/robot/autonomous/paths/score/CenterDriveOff.java
  src/main/java/frc/robot/subsystems/CellSuperstructure.java
  src/main/java/frc/robot/subsystems/Climber.java
  src/main/java/frc/robot/subsystems/cellmech/Hopper.java
Labels: cleanup, feature
