Repository frc5024/InfiniteRecharge, pull requests merged in 2020-01, with the labels that each got.

#20 Tweak init code, and set brakes
  src/main/java/frc/robot/Robot.java
Labels: bug, feature, small task

#22 Do the drive cleanup we talked about in 2019
  src/main/java/frc/lib5k/components/GearBox.java
  src/main/java/frc/lib5k/components/GearBoxEncoder.java
  src/main/java/frc/lib5k/components/RaiderDrive.java
  src/main/java/frc/lib5k/components/drive/DifferentialDriveCalculation.java
  src/main/java/frc/lib5k/components/drive/InputUtils.java
  src/main/java/frc/lib5k/kinematics/DriveSignal.java
  src/main/java/frc/robot/Robot.java
Labels: feature, library

#23 Update NavX wrapper to support WPILib odometry
  imgui.ini
  src/main/java/frc/lib5k/components/gyroscopes/NavX.java
  src/main/java/frc/lib5k/components/gyroscopes/interfaces/IGyroscope.java
  src/main/java/frc/lib5k/components/gyroscopes/interfaces/IHeadingErrorCalculator.java
  src/main/java/frc/robot/Robot.java
Labels: feature, library

#27 Update WPILib to version 2020.1.2
  .wpilib/wpilib_preferences.json
  README.md
  build.gradle
Labels: bug

#32 Merge Kickoff day 1 changes
  imgui.ini
  src/main/java/frc/robot/RobotConstants.java
  src/main/java/frc/robot/autonomous/Chooser.java
  src/main/java/frc/robot/subsystems/DriveTrain.java
Labels: feature

#38 Add fake simulation support for talonSRXCollection
  imgui.ini
  src/main/java/frc/lib5k/components/motors/TalonSRXCollection.java
  src/main/java/frc/lib5k/simulation/Hooks.java
Labels: feature, library

#46 Fix vendor lib issues, and clean up color threshold handling
  .kotlin-for-frc/kotlin-frc-preferences.json
  .wpilib/wpilib_preferences.json
  README.md
  build.gradle
  imgui.ini
  networktables.ini
  networktables.ini.bak
  src/main/java/frc/lib5k/components/ColorSensor5k.java
  src/main/java/frc/robot/RobotConstants.java
  src/main/java/frc/robot/subsystems/PanelManipulator.java
  vendordeps/Phoenix.json
  vendordeps/REVRobotics.json
Labels: feature, invalid, library

#42 Add autonomous mode selection and the start of path generation
  imgui.ini
  src/main/java/frc/lib5k/components/motors/TalonSRXCollection.java
  src/main/java/frc/robot/FieldConstants.java
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/RobotConstants.java
  src/main/java/frc/robot/autonomous/AutonomousStartpoints.java
  src/main/java/frc/robot/autonomous/Chooser.java
  src/main/java/frc/robot/subsystems/DriveTrain.java
Labels: feature, needs documentation

#47 Added auton command generation, and tested on minibot
  src/main/java/frc/lib5k/components/motors/TalonSRXCollection.java
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/RobotConstants.java
  src/main/java/frc/robot/autonomous/Chooser.java
  src/main/java/frc/robot/autonomous/actions/LogCommand.java
  src/main/java/frc/robot/commands/DriveControl.java
  src/main/java/frc/robot/subsystems/DriveTrain.java
Labels: feature, library

#34 Add DriveTrain code, position tracking, and autonomous position setting
  imgui.ini
  src/main/java/frc/lib5k/components/motors/TalonSRXCollection.java
  src/main/java/frc/lib5k/components/motors/VictorSPXCollection.java
  src/main/java/frc/lib5k/components/sensors/IEncoderProvider.java
  src/main/java/frc/lib5k/simulation/Hooks.java
  src/main/java/frc/robot/FieldConstants.java
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/RobotConstants.java
  src/main/java/frc/robot/autonomous/AutonomousStartpoints.java
  src/main/java/frc/robot/autonomous/Chooser.java
  src/main/java/frc/robot/autonomous/actions/LogCommand.java
  src/main/java/frc/robot/commands/DriveControl.java
  src/main/java/frc/robot/subsystems/DriveTrain.java
Labels: feature, library, needs documentation

#44 Created Stubs for Intake and Climber
  src/main/java/frc/robot/subsystems/Climber.java
  src/main/java/frc/robot/subsystems/Intake.java
Labels: feature, needs documentation, small task

#52 Move "magic values" for sensor to RobotConstants
  README.md
  imgui.ini
  src/main/java/frc/lib5k/components/gyroscopes/NavX.java
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/RobotConstants.java
  src/main/java/frc/robot/subsystems/DriveTrain.java
Labels: feature, library

#53 Add HALSIM support to EncoderBase
  README.md
  imgui.ini
  src/main/java/frc/lib5k/components/motors/motorsensors/TalonEncoder.java
  src/main/java/frc/lib5k/components/motors/motorsensors/VictorEncoder.java
  src/main/java/frc/lib5k/components/sensors/EncoderBase.java
  src/main/java/frc/lib5k/simulation/mock/sensors/MockEncoder.java
  src/main/java/frc/robot/RobotConstants.java
  src/main/java/frc/robot/subsystems/DriveTrain.java
Labels: bug, feature, library, needs documentation

#56 Add a simple simulation GUI for robot driving
  images/2020field.png
  requirements.txt
  src/main/java/frc/lib5k/components/gyroscopes/NavX.java
  src/main/python/fieldsim/fieldsim.py
  start-fieldsim.sh
Labels: feature

#55 Simulate NavX hardware
  images/2020field.png
  imgui.ini
  requirements.txt
  src/main/java/frc/lib5k/components/drive/IDifferentialDrivebase.java
  src/main/java/frc/lib5k/components/gyroscopes/NavX.java
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/subsystems/DriveTrain.java
  src/main/python/fieldsim/fieldsim.py
  start-fieldsim.sh
Labels: feature, library

#59 Update FieldSim to better reflect gameplay
  images/gimp-projects/robot-sprite.xcf
  images/robot-sprite.png
  imgui.ini
  src/main/java/frc/lib5k/components/motors/TalonSRXCollection.java
  src/main/python/fieldsim/fieldsim.py
Labels: feature

#62 Constants
  src/main/java/frc/robot/RobotConstants.java
Labels: feature

#64 Tune NavX rotation multiplier
  src/main/java/frc/lib5k/components/gyroscopes/NavX.java
  src/main/java/frc/robot/Robot.java
Labels: feature

#69 Tune trajectory following and make generation more user-friendly
  imgui.ini
  src/main/java/frc/lib5k/components/motors/MixedMotorCollection.java
  src/main/java/frc/lib5k/components/motors/SparkCollection.java
  src/main/java/frc/lib5k/components/motors/TalonSRXCollection.java
  src/main/java/frc/lib5k/roborio/RR_HAL.java
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/RobotConstants.java
  src/main/java/frc/robot/autonomous/Chooser.java
  src/main/java/frc/robot/autonomous/PathGenerator.java
  src/main/java/frc/robot/autonomous/helpers/EasyTrajectory.java
  src/main/java/frc/robot/autonomous/helpers/PathGenerator.java
  src/main/java/frc/robot/autonomous/helpers/SpeedConstraint.java
  src/main/java/frc/robot/subsystems/DriveTrain.java
  src/main/python/fieldsim/fieldsim.py
Labels: cleanup, documentation, feature, library

#68 Fixed simulation voltage data
  src/main/java/frc/lib5k/components/motors/MixedMotorCollection.java
  src/main/java/frc/lib5k/components/motors/SparkCollection.java
  src/main/java/frc/lib5k/components/motors/TalonSRXCollection.java
  src/main/java/frc/lib5k/roborio/RR_HAL.java
Labels: bug

#71 Added tuning for turning
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/RobotConstants.java
  src/main/java/frc/robot/autonomous/Chooser.java
  src/main/java/frc/robot/autonomous/helpers/PathGenerator.java
Labels: cleanup

#76 Add a proper autonomous path for demonstration
  src/main/java/frc/lib5k/kinematics/MovementPlanner.java
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/RobotConstants.java
  src/main/java/frc/robot/autonomous/AutonomousStartpoints.java
  src/main/java/frc/robot/autonomous/Chooser.java
  src/main/java/frc/robot/autonomous/actions/LinePath.java
  src/main/java/frc/robot/autonomous/actions/MotionSolveCommand.java
  src/main/java/frc/robot/autonomous/actions/TrapezoidPath.java
  src/main/java/frc/robot/autonomous/actions/TrianglePath.java
  src/main/java/frc/robot/autonomous/helpers/PathGenerator.java
  src/main/python/fieldsim/fieldsim.py
Labels: cleanup, feature, library

#77 Remove most of the autonomous path overshoot (saves 1.5 seconds from the demo path)
  src/main/java/frc/robot/RobotConstants.java
  src/main/java/frc/robot/autonomous/Chooser.java
  src/main/java/frc/robot/autonomous/actions/TurnToCommand.java
Labels: cleanup

#75 Do more cleanup, Add a fancy autonomous demo, and add turn wrapping
  .vscode/launch.json
  src/main/java/frc/lib5k/kinematics/MovementPlanner.java
  src/main/java/frc/lib5k/utils/Mathutils.java
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/RobotConstants.java
  src/main/java/frc/robot/autonomous/AutonomousStartpoints.java
  src/main/java/frc/robot/autonomous/Chooser.java
  src/main/java/frc/robot/autonomous/actions/LinePath.java
  src/main/java/frc/robot/autonomous/actions/MotionSolveCommand.java
  src/main/java/frc/robot/autonomous/actions/TrapezoidPath.java
  src/main/java/frc/robot/autonomous/actions/TrianglePath.java
  src/main/java/frc/robot/autonomous/actions/TurnToCommand.java
  src/main/java/frc/robot/autonomous/helpers/EasyTrajectory.java
  src/main/java/frc/robot/autonomous/helpers/PathGenerator.java
  src/main/python/fieldsim/fieldsim.py
Labels: cleanup, documentation, feature, library

#81 Document all week1 path planning classes
  src/main/java/frc/robot/autonomous/Chooser.java
  src/main/java/frc/robot/autonomous/actions/LinePath.java
  src/main/java/frc/robot/autonomous/actions/LogCommand.java
  src/main/java/frc/robot/autonomous/actions/MotionSolveCommand.java
  src/main/java/frc/robot/autonomous/actions/TrapezoidPath.java
  src/main/java/frc/robot/autonomous/actions/TrianglePath.java
  src/main/java/frc/robot/autonomous/actions/TurnToCommand.java
  src/main/java/frc/robot/autonomous/helpers/PathGenerator.java
Labels: cleanup, documentation

#79 Created the Stub for Shooter
  src/main/java/frc/robot/subsystems/Climber.java
  src/main/java/frc/robot/subsystems/Shooter.java
Labels: feature, small task

#84 Tuned PID to turn faster
  src/main/java/frc/robot/RobotConstants.java
  src/main/java/frc/robot/autonomous/Chooser.java
  src/main/java/frc/robot/autonomous/actions/TurnToCommand.java
Labels: cleanup

#86 add more stubs to shooter, and implement JRAD controller
  src/main/java/frc/lib5k/control/JRADController.java
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/subsystems/Shooter.java
Labels: cleanup, feature, library

#88 Fix startpoints to match field locations and fieldsim
  src/main/java/frc/robot/autonomous/AutonomousStartpoints.java
  src/main/java/frc/robot/autonomous/Chooser.java
  src/main/java/frc/robot/autonomous/paths/AutonomousPath.java
  src/main/java/frc/robot/autonomous/paths/slow/SlowRight.java
Labels: cleanup, documentation, feature

#85 Cleaned up color sensing code
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/subsystems/PanelManipulator.java
Labels: cleanup, documentation

#95 Do a huge cleanup to FieldSim
  .gitignore
  .vscode/settings.json
  fieldsim/Colors.py
  fieldsim/Draw.py
  fieldsim/Field.py
  fieldsim/NetUtil.py
  fieldsim/RobotConn.py
  fieldsim/__main__.py
  fieldsim/assets/fields/2020field-base.png
  fieldsim/assets/fields/2020field-cfg.json
  fieldsim/assets/fields/2020field-top.png
  fieldsim/assets/robot-sprite.png
  fieldsim/old.py
  start-fieldsim.bat
  start-fieldsim.sh
Labels: cleanup, documentation

#97 Fix NPE that made it's way into master
  src/main/java/frc/robot/subsystems/PanelManipulator.java
  src/main/java/frc/robot/subsystems/Shooter.java
Labels: bug, cleanup

#99 Make a superstructure for only cells
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/subsystems/CellSuperstructure.java
  src/main/java/frc/robot/subsystems/cellmech/Hopper.java
  src/main/java/frc/robot/subsystems/cellmech/Intake.java
  src/main/java/frc/robot/subsystems/cellmech/Shooter.java
Labels: cleanup

#101 Add a new auton path to get balls and shoot from the trench
  src/main/java/frc/robot/autonomous/Chooser.java
  src/main/java/frc/robot/autonomous/helpers/SpeedConstraint.java
  src/main/java/frc/robot/autonomous/paths/slow/SlowRightHalffield.java
Labels: cleanup, feature

#102 Add shooter subsystem code and controller for demoing
  imgui.ini
  src/main/java/frc/lib5k/control/JRADController.java
  src/main/java/frc/lib5k/simulation/wrappers/SimTalon.java
  src/main/java/frc/robot/OI.java
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/RobotConstants.java
  src/main/java/frc/robot/commands/ShooterTester.java
  src/main/java/frc/robot/subsystems/cellmech/Shooter.java
Labels: cleanup, feature, library

#109 Added ability to drive backwards, and modified path to support it
  imgui.ini
  src/main/java/frc/robot/RobotConstants.java
  src/main/java/frc/robot/autonomous/Chooser.java
  src/main/java/frc/robot/autonomous/actions/DriveDistance.java
  src/main/java/frc/robot/autonomous/paths/slow/SlowRight.java
  src/main/java/frc/robot/autonomous/paths/test/TestReverse.java
  src/main/java/frc/robot/subsystems/DriveTrain.java
Labels: feature, library

#107 VisionAlign Auto Task
  src/main/java/frc/robot/autonomous/actions/VisionAlign.java
  src/main/java/frc/robot/subsystems/cellmech/Shooter.java
Labels: feature

#115 Add a command to drive to a point from an unknown starting pose
  src/main/java/frc/robot/autonomous/actions/DriveToCommand.java
  src/main/java/frc/robot/autonomous/paths/slow/SlowRightHalffield.java
Labels: feature

#112 Refactor auto aiming, and add method to automatically drive to an "ideal" scoring zone
  InfiniteRecharge.iml
  InfiniteRecharge.ipr
  InfiniteRecharge.iws
  InfiniteRecharge.main.iml
  InfiniteRecharge.test.iml
  src/main/java/frc/lib5k/components/limelight/Limelight.java
  src/main/java/frc/lib5k/kinematics/purepursuit/Path.java
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/RobotConstants.java
  src/main/java/frc/robot/autonomous/actions/DriveToCommand.java
  src/main/java/frc/robot/autonomous/actions/TurnToCommand.java
  src/main/java/frc/robot/autonomous/actions/VisionAlign.java
  src/main/java/frc/robot/autonomous/paths/slow/SlowRight.java
  src/main/java/frc/robot/autonomous/paths/slow/SlowRightHalffield.java
  src/main/java/frc/robot/subsystems/DriveTrain.java
  src/main/java/frc/robot/vision/Limelight2.java
  src/main/java/frc/robot/vision/LimelightTarget.java
  src/main/java/frc/robot/vision/TargetTracker.java
  src/main/limelight/UpperTarget.vpr
  src/main/limelight/pnp_2020_hex_fourpointTOP.csv
Labels: cleanup, documentation, feature, library

#117 Auton paths
  imgui.ini
  src/main/java/frc/robot/RobotConstants.java
  src/main/java/frc/robot/autonomous/AutonomousStartpoints.java
  src/main/java/frc/robot/autonomous/Chooser.java
  src/main/java/frc/robot/autonomous/paths/score/ScoreRight.java
  src/main/java/frc/robot/autonomous/paths/slow/SlowRight.java
  src/main/java/frc/robot/autonomous/paths/slow/SlowRightHalffield.java
  src/main/java/frc/robot/autonomous/paths/test/TestPID.java
  src/main/java/frc/robot/subsystems/DriveTrain.java
Labels: feature

#121 Force shooter to compensate voltage for testing
  src/main/java/frc/robot/commands/ShooterTester.java
  src/main/java/frc/robot/subsystems/cellmech/Shooter.java
Labels: feature

#118 Auton paths
  characterization/MinibotCarpet20200124-1730.json
  characterization/robotconfig.py
  imgui.ini
  src/main/java/frc/robot/RobotConstants.java
  src/main/java/frc/robot/autonomous/AutonomousStartpoints.java
  src/main/java/frc/robot/autonomous/Chooser.java
  src/main/java/frc/robot/autonomous/paths/score/ScoreCenter.java
  src/main/java/frc/robot/autonomous/paths/score/ScoreGetBalls.java
  src/main/java/frc/robot/autonomous/paths/score/ScorePickupRight.java
  src/main/java/frc/robot/autonomous/paths/slow/SlowRight.java
Labels: feature

#122 Get the climber up to date with master
  InfiniteRecharge.iml
  InfiniteRecharge.ipr
  InfiniteRecharge.iws
  InfiniteRecharge.main.iml
  InfiniteRecharge.test.iml
  characterization/MinibotCarpet20200124-1730.json
  characterization/robotconfig.py
  imgui.ini
  src/main/java/frc/lib5k/components/limelight/Limelight.java
  src/main/java/frc/lib5k/kinematics/purepursuit/Path.java
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/RobotConstants.java
  src/main/java/frc/robot/autonomous/AutonomousStartpoints.java
  src/main/java/frc/robot/autonomous/Chooser.java
  src/main/java/frc/robot/autonomous/actions/DriveToCommand.java
  src/main/java/frc/robot/autonomous/actions/TurnToCommand.java
  src/main/java/frc/robot/autonomous/actions/VisionAlign.java
  src/main/java/frc/robot/autonomous/paths/score/ScoreCenter.java
  src/main/java/frc/robot/autonomous/paths/score/ScoreGetBalls.java
  src/main/java/frc/robot/autonomous/paths/score/ScorePickupRight.java
  src/main/java/frc/robot/autonomous/paths/score/ScoreRight.java
  src/main/java/frc/robot/autonomous/paths/slow/SlowRight.java
  src/main/java/frc/robot/autonomous/paths/slow/SlowRightHalffield.java
  src/main/java/frc/robot/autonomous/paths/test/TestPID.java
  src/main/java/frc/robot/commands/ShooterTester.java
  src/main/java/frc/robot/subsystems/Climber.java
  src/main/java/frc/robot/subsystems/DriveTrain.java
  src/main/java/frc/robot/subsystems/cellmech/Shooter.java
  src/main/java/frc/robot/vision/Limelight2.java
  src/main/java/frc/robot/vision/LimelightTarget.java
  src/main/java/frc/robot/vision/TargetTracker.java
  src/main/limelight/UpperTarget.vpr
  src/main/limelight/pnp_2020_hex_fourpointTOP.csv
Labels: bug, cleanup

#123 Give the climber a state machine
  src/main/java/frc/lib5k/components/AutoCamera.java
  src/main/java/frc/lib5k/components/pneumatics/LazySolenoid.java
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/RobotConstants.java
  src/main/java/frc/robot/commands/ClimbSystem.java
  src/main/java/frc/robot/subsystems/Climber.java
Labels: cleanup, documentation, feature

#119 Add automatic aiming and motion
  src/main/java/frc/robot/OI.java
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/RobotConstants.java
  src/main/java/frc/robot/commands/AutoAlign.java
  src/main/java/frc/robot/commands/DriveControl.java
  src/main/java/frc/robot/subsystems/DriveTrain.java
  src/main/java/frc/robot/vision/Limelight2.java
  vendordeps/Phoenix.json
  vendordeps/REVColorSensorV3.json
Labels: feature

#125 Fix up the climb commands, and pull up to master
  imgui.ini
  src/main/java/frc/robot/OI.java
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/RobotConstants.java
  src/main/java/frc/robot/commands/AutoAlign.java
  src/main/java/frc/robot/commands/ClimbController.java
  src/main/java/frc/robot/commands/ClimbProcess.java
  src/main/java/frc/robot/commands/DriveControl.java
  src/main/java/frc/robot/subsystems/Climber.java
  src/main/java/frc/robot/subsystems/DriveTrain.java
  src/main/java/frc/robot/subsystems/cellmech/Shooter.java
  src/main/java/frc/robot/vision/Limelight2.java
  vendordeps/Phoenix.json
  vendordeps/REVColorSensorV3.json
Labels: cleanup
